name: 'Setup GWT Dev Environment'
description: 'Checks out GWT and GWT Tools, sets up Nix and Cachix'
inputs:
  cachix_auth_token:
    description: 'Cachix auth token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare Nix environment
      id: setenv
      run: |
        : check for nix backup file
        set -ex -o pipefail
        cat <<! | cut -c 3- | tee -a "$GITHUB_OUTPUT"
          nix-installed=$( [[ -f "/etc/bash.bashrc.backup-before-nix" ]] && echo true || echo false )
        !
        cat <<! | cut -c 3- | tee -a "$GITHUB_PATH"
          /home/runner/.nix-profile/bin
          /nix/var/nix/profiles/default/bin
        !
        cat <<! | cut -c 3- | tee -a "$GITHUB_ENV"
          NIX_PATH=$HOME/.nix-profile/bin
          GWT_TOOLS=$( realpath ../tools )
        !
      shell: bash -xe -o pipefail {0}

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      if: steps.setenv.outputs.nix-installed == 'false'
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Install Cachix
      uses: cachix/cachix-action@v12
      with:
        name: gwt-nuxeo
        authToken: '${{ inputs.cachix_auth_token }}'
