name: 'Deploy Maven Artifacts'
description: 'Deploy Maven artifacts to a repository'
inputs:
  server:
    description: 'Maven server configuration in YAML format'
    required: true
  cachix_auth_token:
    description: 'Cachix auth token'
    required: false
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/nix-develop
      with:
        cachix_auth_token: ${{ inputs.cachix_auth_token }}

    - name: Download GWT artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: ./dist

    - name: Deploy artifacts
      shell: nix develop .devenv#default -c bash -xe -o pipefail {0}
      env:
        SERVER: ${{ inputs.maven_server_config }}
      run: |
        : Update maven settings
        mkdir -p ~/.m2
        if [ ! -f ~/.m2/settings.xml ]; then
          echo '<settings><servers></servers></settings>' > ~/.m2/settings.xml
        fi

        : Merge the new server into the existing settings
        yq eval-all '
          select(fileIndex == 0).settings.servers.server |= 
            (if . == null then [] else . end) + 
            [select(fileIndex == 1)] | 
          select(fileIndex == 0)
        ' <(yq --input-format=xml --output-format=yaml eval ~/.m2/settings.xml) <<<"${MAVEN_SERVER_CONFIG}" |
          yq --input-format=yaml --output-format=xml eval . > ~/.m2/settings.xml

        : Extract and set environment variables
        eval $(yq eval 'to_entries[] | "export GWT_MAVEN_REPO_" + (.key | upcase) + "=\"" + .value + "\""' <(echo "$MAVEN_SERVER_CONFIG"))

        : Deploy the artifacts
        ./maven/push-gwtproject.sh

